# Generated by Django 2.1.2 on 2019-03-08 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sign_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=64)),
                ('start_time', models.DateTimeField(verbose_name='%Y-%m-%d %H:%M:%S')),
            ],
        ),
    ]
