# Generated by Django 2.1.2 on 2019-03-08 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0001_initial'),
    ]

    operations = [
    ]
