# Generated by Django 2.1.2 on 2019-03-08 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0002_auto_20190308_0340'),
    ]

    operations = [
    ]
